spring:
  application:
    name: trip

  datasource:
    url: jdbc:h2:file:./data/trip
    username: sa
    password: ""

  sql:
    init:
      # 실행마다 schema.sql을 실행
      mode: always

  jpa:
    hibernate:
      ddl-auto: validate
    # OSIV 해제
    open-in-view: false

  threads:
    virtual:
      enabled: true

supplier:
  endpoints:
    A:
      base-url: http://localhost:9090
      api-key: dev-key-a
    B:
      base-url: http://localhost:9090
      api-key: dev-key-b
  connect-timeout: 1s
  response-timeout: 3s
